name: smoke-test

on:
  push:
    branches: main

jobs:
  smoke-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install Control Packs
        run: |
          cd ..; mkdir opencspm-controls; cd opencspm-controls; git clone https://github.com/OpenCSPM/opencspm-darkbit-community-controls.git
      - name: Docker Compose Up
        run: |
          cd docker; docker-compose up -d
      - name: Smoke Test (10 min)
        run: |
          timeout 600 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:5000/statusz)" != "200" ]]; do sleep 5; done' || false
